- name: Deploy app to Azure VM
  hosts: web
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull app image from ACR
      shell: docker login youracr.azurecr.io -u <ACR_USER> -p <ACR_PASS> && docker pull {{ image }}

    - name: Run Docker container
      shell: docker run -d -p 80:5000 {{ image }}

